= Expense Tracker UI
:toc:

Expense Tracker UI is the front-end for the Expense Tracker application from KTRI Industries.
The Expense Tracker application allows for easy monitoring of expenses, while also providing insights and analytics into personal and household spending habits.

== The tech stack

Expense Tracker UI is an Angular application created as an link:https://nx.dev/getting-started/tutorials/angular-standalone-tutorial[Nx stand-alone project].
It uses link:https://ngrx.io/[NgRx] for state management, link:https://jestjs.io/[Jest] for unit testing and link:https://www.cypress.io/[Cypress] for end-to-end testing.

We opted to use Nx because:

- it provides out of the box support for ESLint, Jest and Cypress
- it offers advanced tooling like caching support for builds, linting and testing, as well as integration with various CI platforms

== Dev Environment setup and deployment
=== Setup for NgRx state management
To perform the initial configuration for NgRx with standalone app component, the following command was executed:
[source,shell]
nx g @nx/angular:ngrx-root-store  --facade=true  --addDevTools=true --project=expense-tracker-ui

The above command adds all necessary dependencies and performs initial configuration by registering the store and effects providers in the main app standalone component.

== Prod environment setup and deployment

TODO

== Generate a standalone library

----
npx nx g @nx/angular:library --name=auth --directory=libs/shared --simpleName=true --standalone=true
----

== Generate a ngrx feature store for a library

----
npx nx g @nx/angular:ngrx-feature-store --name=auth --parent=libs/shared/auth/src/lib/lib.routes.ts --barrels=true
----

