// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: a0baeabd1218c132daadbc141cb6287a92d7cc9756bdcf055e17de073d2dd490

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import type {
  ApplicationRef,
  ComponentRef,
  EnvironmentProviders,
  Type,
} from '@angular/core';

export type ThemeName = 'expense-tracker';

export const themeNames: ThemeName[] = ['expense-tracker'];

export type KcEnvName = 'UI_THEME';

export const kcEnvNames: KcEnvName[] = ['UI_THEME'];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  UI_THEME: 'navy',
};

export type KcContext = import('./login/KcContext').KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export async function bootstrapKcApplication(params: {
  kcContext: KcContext;
  bootstrapApplication: (params: {
    KcRootComponent: Type<unknown>;
    kcProvider: EnvironmentProviders;
  }) => Promise<ApplicationRef>;
}): Promise<ApplicationRef> {
  const { kcContext, bootstrapApplication } = params;
  let appRef: ApplicationRef;

  switch (kcContext.themeType) {
    case 'login':
      {
        const [
          { provideKeycloakifyAngular },
          { getI18n },
          {
            PageComponent,
            TemplateComponent,
            doUseDefaultCss,
            classes,
            UserProfileFormFieldsComponent,
            doMakeUserConfirmPassword,
          },
        ] = await Promise.all([
          import('@keycloakify/angular/login/providers/keycloakify-angular'),
          import('./login/i18n'),
          import('./login/KcPage').then(({ getKcPage }) =>
            getKcPage(kcContext.pageId),
          ),
        ] as const);

        appRef = await bootstrapApplication({
          KcRootComponent: TemplateComponent,
          kcProvider: provideKeycloakifyAngular({
            kcContext,
            classes,
            getI18n,
            doUseDefaultCss,
            doMakeUserConfirmPassword,
          }),
        });

        appRef.components.forEach((componentRef) => {
          // page must be defined first
          if ('page' in componentRef.instance) {
            componentRef.setInput('page', PageComponent);
          }
          if ('userProfileFormFields' in componentRef.instance) {
            componentRef.setInput(
              'userProfileFormFields',
              UserProfileFormFieldsComponent,
            );
          }
        });
      }
      break;
    default:
      throw new Error('wrong themeType');
  }

  return appRef;
}
