name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_DISABLE_DB: true
    steps:
      - uses: actions/checkout@v5
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - run: rm -rf node_modules
      - run: rm package-lock.json
      - run: npm install

#      - run: npx nx format:check this fails for no obvious reason
      - run: npx nx affected -t lint --parallel=3 --skip-nx-cache
      - run: npx nx affected -t test --parallel=3 --skip-nx-cache
      - run: npx nx affected -t build --parallel=3 --skip-nx-cache
